// Per-stop tour-guide content (English) — content goes to English so the TTS
// sounds natural; the Hebrew system voice is robotic and unbearable for long
// audio. UI labels and the schedule narrative stay Hebrew.
//
// Hand-authored by Claude (no API tokens consumed — those are reserved for
// mom's runtime "what's in the area" rescue button).

const TRIP_GUIDES = {
  "d2-s2": {
    "intro": "Park Avenue Trail is one mile of walking through a corridor of sandstone walls about 100 meters tall on each side. The name 'Park Avenue' is not a metaphor — the surveyors who first walked here in the 1920s looked up and saw skyscrapers. The difference is that 165 million years of wind, sand and pressure did the work here, instead of New York construction crews.",
    "history": "Arches was declared a National Monument in 1929 by President Herbert Hoover, and upgraded to National Park status on November 12, 1971 by Nixon. The most interesting story belongs to Edward Abbey — a writer and desert philosopher who worked here as a seasonal ranger in the summers of 1956 and 1957. A decade later, in 1968, he turned those two seasons of notes into 'Desert Solitaire', the bible of American desert lovers. In his first season there was no paved road into the park; he drove a dirt track. In 1958, the year after he left, they cut the road you're driving on now. Abbey wrote that this 'accessibility' ruined the park forever. Many features in the park were named in 1933-34 by Frank Beckwith, editor of the Millard County Chronicle, who led the Arches Scientific Expedition. The Ute and Pueblo peoples crossed this wash for centuries as a corridor between the Colorado basin and the high plateaus.",
    "geology": "The walls around you are Entrada Sandstone — red-orange rock formed about 165 million years ago in the Jurassic period. Back then, this area was a vast tidal flat on the edge of a shallow sea covering all of western North America. Each horizontal stripe in the wall is a separate layer — months or years when sand piled up a certain way before being buried by the next layer. The wash you're walking in is actually a trained creek. After rain it becomes a flowing stream within an hour — a flash flood. Every shape around you was carved by that water over tens of millions of years. The rock is still eroding. The walls will eventually crumble back to sand, wash downstream, and become new sandstone somewhere else. The geology here is a cycle, not a final product.",
    "lookFor": [
      "From the overlook at the start of the trail, before descending into the wash, look right at the eastern wall. In the morning the sun lights it gold on one side while the other side stays in deep shadow. The color contrast is dramatic — and gone by afternoon.",
      "As you walk down the wash, look at the trail surface. If you find shiny red sand grains, that's sand that used to be the wall. You're walking on the remains of the rocks around you, broken down one grain at a time over millions of years.",
      "Watch the pattern of stripes in the walls. Most are horizontal — tidal layers. But in some sections you'll see diagonal stripes, what geologists call 'cross-bedding'. Those are the remains of ancient sand dunes that fossilized within the layer. Each diagonal line is a dune that vanished.",
      "At the southern end, the wash opens into a wide viewpoint. To your left you'll see 'The Organ' — a massive rock that looks like a church organ. To your right is 'Tower of Babel', a solitary tower rising above the brush. These two are the stars of the Courthouse Towers area.",
      "Listen — total silence. No birds in the walls because there are no trees, and no flowing water right now. The only sound is wind crashing on stone. This is one of the quietest places in the entire park."
    ],
    "momTip": "The trail is one-way, one mile, north to south. If you parked a second car at the south end (Courthouse Towers Viewpoint), do the one-way and skip the return walk. If not, turn around at the south end and walk back the same way (2 miles round trip). Best photos are in the first hour after sunrise: the sun hits the western wall and turns it gold while the eastern wall stays in shadow. Midday colors are flat. Don't try climbing the walls — sandstone breaks easily even under light pressure, and nobody will reach you quickly out here."
  },

  "d2-s7": {
    "intro": "Double Arch is not an arch — it's two arches springing from the same base of rock, holding each other up in mechanics that look almost impossible. The bigger one is 34 meters tall, the height of a ten-story building. When you stand underneath, your neck hurts from looking up. This is one of Utah's iconic images.",
    "history": "This place broke into the wider world in 1989, when Steven Spielberg chose it for the opening scene of 'Indiana Jones and the Last Crusade'. River Phoenix as young Indy rode a horse through these red rocks — filmed right here at Double Arch and the nearby Windows section. Audiences worldwide saw the arch without knowing what they were looking at, and tourism to the park jumped. Most named features in this part of Arches got their names in 1933-34 from Frank Beckwith, editor of the Millard County Chronicle, who led the Arches Scientific Expedition. The Ancestral Puebloan peoples crossed this valley for centuries on their way from the Colorado basin to the higher hunting grounds — they left rock art and camp remains elsewhere in the park, but not here. This area was a passage point, not a settlement.",
    "geology": "The rock is Entrada Sandstone from the Jurassic — about 160 million years ago, this area was a sea of enormous sand dunes, like today's Sahara. Wind buried layer on layer, pressure turned sand into stone, and then — slowly — water, ice, and the temperature swing between day and night broke down whatever was less stable. The two arches were born from a single 'window' that started as a small crack in a rock wall and was widened over time. When the opening grew large enough, part of the ceiling collapsed and split it in two — that's what creates the 'twin'. In another few hundred or thousand years, the rock will keep eroding and one of the arches will eventually fall. We're seeing them at one specific moment in their life cycle.",
    "lookFor": [
      "Stand right in the center, directly under the meeting point of the two arches. Feel the scale — the bigger arch is 34 meters tall. Photograph straight up — that's the classic shot.",
      "Look at the rock color — it's not uniform. The dark stripes flowing down the walls are 'desert varnish' — a thin layer of manganese and iron painted on over thousands of years by tiny rain droplets seeping down the stone.",
      "Find the smaller arch on the left. It's hidden in the official photos, but it's beautiful on its own — look through it and you'll see a third strip of blue sky framed inside an arch within an arch.",
      "Watch the shadows in the opening. In early morning, the shadow cuts across the rock face at a dramatic angle that highlights every wrinkle and bulge. By midday the light is too flat and the texture disappears.",
      "Leave your hiking poles in the car — the trail is too short and easy for them, and once you arrive you'll want both hands free for photos."
    ],
    "momTip": "The trail is 0.5 miles each way, completely flat, suitable for any age. The best photo spot is not near the trailhead but after walking about 200 meters and turning right toward the base of the arches themselves — there you can sit on the rock and shoot straight up with sky filling the frame. The hour before sunset gives low golden light that plays on the red rock. Don't try climbing the arch — it looks stable but the rock surface crumbles easily, and there's a federal fine for climbing arches in the park."
  }
};

if (typeof module !== 'undefined') module.exports = TRIP_GUIDES;
