// Generate rich tour-guide content (Hebrew) for every stop in the trip.
//
// For each stop we call Claude Sonnet 4.6 with prompt caching on a long Hebrew
// system prompt that defines the tour-guide voice, output schema, and tone.
// Output is written incrementally to js/guides.js so a crash mid-run doesn't
// lose work — re-runs skip stops already generated.
//
// Usage:
//   node tools/generate-guides.js              (run all missing stops)
//   node tools/generate-guides.js --day 2      (only Day 2)
//   node tools/generate-guides.js --stop d2-s4 (only that stop)
//   node tools/generate-guides.js --redo d2-s4 (regenerate one stop)
//   node tools/generate-guides.js --limit 5    (cap stops per run, for testing)

const fs = require('fs');
const path = require('path');
const Anthropic = require('@anthropic-ai/sdk').default;

// --- env ---
const envPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z_]+)\s*=\s*(.+?)\s*$/);
    if (m) process.env[m[1]] = m[2];
  }
}
if (!process.env.ANTHROPIC_API_KEY) {
  console.error('Missing ANTHROPIC_API_KEY (looked in .env and process env)');
  process.exit(1);
}

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const MODEL = 'claude-sonnet-4-6';

// --- args ---
const argv = process.argv.slice(2);
function arg(flag) {
  const i = argv.indexOf(flag);
  return i >= 0 ? argv[i + 1] : null;
}
const ONLY_DAY = arg('--day') ? parseInt(arg('--day'), 10) : null;
const ONLY_STOP = arg('--stop');
const REDO_STOP = arg('--redo');
const LIMIT = arg('--limit') ? parseInt(arg('--limit'), 10) : Infinity;

// --- data ---
const TRIP = require(path.join(__dirname, '..', 'js', 'data.js'));

const GUIDES_PATH = path.join(__dirname, '..', 'js', 'guides.js');
function loadExistingGuides() {
  if (!fs.existsSync(GUIDES_PATH)) return {};
  const src = fs.readFileSync(GUIDES_PATH, 'utf8');
  const m = src.match(/const TRIP_GUIDES\s*=\s*(\{[\s\S]*?\});\s*\n\s*if/);
  if (!m) return {};
  try { return JSON.parse(m[1]); } catch (e) { return {}; }
}
function saveGuides(guides) {
  const out =
    `// AUTO-GENERATED by tools/generate-guides.js — do not hand-edit.\n` +
    `// Per-stop tour-guide content in Hebrew: intro, history, geology, lookFor[], momTip.\n\n` +
    `const TRIP_GUIDES = ${JSON.stringify(guides, null, 2)};\n\n` +
    `if (typeof module !== 'undefined') module.exports = TRIP_GUIDES;\n`;
  fs.writeFileSync(GUIDES_PATH, out);
}

const guides = loadExistingGuides();

// --- prompt ---
const SYSTEM = [
  {
    type: 'text',
    text:
`את מדריכת תיירים מנוסה ובעלת ידע עמוק בקניוני יוטה, אריזונה ונבדה — היסטוריה ילידית, גיאולוגיה, אקולוגיה וסיפורים מקומיים. את כותבת באנגלית את שמות המקומות (כך אמא תזהה אותם על השלטים), אך כל ההסברים בעברית.

קהל היעד: אישה ישראלית, מטיילת לבד עם הרכב השכור, אוהבת טבע, סקרנית, אבל לא רוצה הרצאות יבשות. היא רוצה את "מאחורי הקלעים" של המקום — מה ראה הראשון שהגיע לכאן, מה קרה כאן לפני 200 שנה, איך הסלע נוצר, ומה בדיוק להסתכל עליו עכשיו.

הוצאי בכל קריאה JSON תקין בלבד (ללא טקסט נוסף לפני או אחרי), עם השדות הבאים:

{
  "intro": "משפט-שניים מושכים שמסבירים למה המקום הזה מיוחד מספיק שמישהו טס מישראל לראות אותו",
  "history": "2-4 משפטים — סיפור היסטורי, תרבותי, או אנקדוטה (גילוי, עמים ילידים, אבן דרך). אם אין סיפור היסטורי משמעותי, החזירי מחרוזת ריקה.",
  "geology": "2-4 משפטים — איך הסלע/הצורה נוצרו, באיזו תקופה, מה הצבעים אומרים. בעברית פשוטה, לא מדעית-קרה.",
  "lookFor": ["3-5 דברים ספציפיים מאוד להסתכל עליהם — לא 'הנוף יפה', אלא 'הסתכלי על הקיר השמאלי בכניסה לקניון — הפסים השחורים הם הצטברות מינרלים מאלפי שנים של מים שזולגים'."],
  "momTip": "טיפ פרקטי אחד-שניים: איפה לעמוד לתמונה הכי טובה, איזה חלק לדלג אם עייפה, איפה הצל. בלי קלישאות."
}

כללים:
- שמרי שמות מקום, שבילים, ופארקים באנגלית בתוך הטקסט העברי (Delicate Arch, Fiery Furnace, Park Avenue Trail).
- אל תמציאי. אם אין לך מידע על משהו ספציפי (פסל, חקיקה), השאירי את השדה ריק במקום להמציא.
- אל תזכירי "אמא" בטקסט עצמו — את כותבת *אליה*, אבל לא עליה.
- כתבי בלשון נקבה יחיד (הסתכלי, שימי לב, חפשי).
- אל תפתחי כל פסקה ב"כאן" או "במקום הזה". גוונים.`,
    cache_control: { type: 'ephemeral' },
  },
];

// --- per-stop context ---
function buildUserPrompt(day, stop) {
  const dayCtx = `יום ${day.dayNumber} (${day.date}) — ${day.title}${day.titleHe ? ` (${day.titleHe})` : ''}`;
  const region = day.region ? `\nאזור: ${day.region}` : '';
  const hotel = day.hotel ? `\nמלון לאותו לילה: ${day.hotel.name}` : '';
  const coords = stop.coordinates ? `\nקואורדינטות: ${stop.coordinates.lat.toFixed(5)}, ${stop.coordinates.lng.toFixed(5)}` : '';
  const type = stop.type ? `\nסוג: ${stop.type}` : '';
  const diff = stop.difficulty ? `\nרמת קושי: ${stop.difficulty}` : '';
  const tip = stop.tip ? `\nהערה קיימת מהתכנון: ${stop.tip}` : '';

  // Pull narrative from the matching schedule row (now in Hebrew for translated days).
  let narrative = '';
  for (const d of TRIP.days) {
    const row = (d.schedule || []).find(r => r.stopId === stop.id && r.text);
    if (row) { narrative = row.text; break; }
  }
  const nar = narrative ? `\nתיאור המסלול ליום: ${narrative}` : '';

  return `שם המקום: ${stop.name}
${dayCtx}${region}${hotel}${type}${diff}${coords}${tip}${nar}

הוצאי JSON עם intro, history, geology, lookFor, momTip — בעברית, על המקום הזה. אל תוסיפי טקסט מחוץ ל-JSON.`;
}

// --- candidate stops ---
function candidateStops() {
  const out = [];
  for (const day of TRIP.days) {
    if (ONLY_DAY && day.dayNumber !== ONLY_DAY) continue;
    for (const stop of (day.stops || [])) {
      if (ONLY_STOP && stop.id !== ONLY_STOP) continue;
      if (REDO_STOP && stop.id !== REDO_STOP) continue;
      if (!stop.coordinates) continue;       // skip stops without a place to anchor to
      if (!stop.name) continue;
      if (guides[stop.id] && !REDO_STOP) continue;  // resume — skip already done
      out.push({ day, stop });
    }
  }
  return out;
}

// --- caller ---
async function generateOne(day, stop) {
  const userPrompt = buildUserPrompt(day, stop);
  const resp = await client.messages.create({
    model: MODEL,
    max_tokens: 1500,
    system: SYSTEM,
    messages: [{ role: 'user', content: userPrompt }],
  });
  const txt = resp.content
    .filter(b => b.type === 'text')
    .map(b => b.text)
    .join('')
    .trim();

  // Strip optional ```json fences.
  const cleaned = txt.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/, '').trim();
  let parsed;
  try { parsed = JSON.parse(cleaned); }
  catch (e) {
    throw new Error(`JSON parse failed for ${stop.id}: ${e.message}\nRaw: ${cleaned.slice(0, 400)}`);
  }
  // Cache stats — Anthropic returns hits as part of usage.
  const u = resp.usage || {};
  const cacheRead = u.cache_read_input_tokens || 0;
  const cacheWrite = u.cache_creation_input_tokens || 0;
  return { guide: parsed, usage: { ...u, cacheRead, cacheWrite } };
}

(async () => {
  const todo = candidateStops().slice(0, LIMIT);
  console.log(`Stops to generate: ${todo.length}`);
  if (!todo.length) { console.log('Nothing to do.'); return; }

  let totalCost = 0;
  for (let i = 0; i < todo.length; i++) {
    const { day, stop } = todo[i];
    const tag = `[${i + 1}/${todo.length}] D${day.dayNumber} ${stop.id} ${stop.name.slice(0, 40)}`;
    process.stdout.write(`${tag} ... `);
    try {
      const { guide, usage } = await generateOne(day, stop);
      guides[stop.id] = { ...guide, _model: MODEL, _at: new Date().toISOString() };
      saveGuides(guides);
      // Sonnet 4.6 pricing: $3/M input, $15/M output, cache reads $0.30/M, writes $3.75/M.
      const costIn  = (usage.input_tokens || 0)        * 3 / 1_000_000;
      const costOut = (usage.output_tokens || 0)       * 15 / 1_000_000;
      const costCR  = (usage.cacheRead || 0)           * 0.30 / 1_000_000;
      const costCW  = (usage.cacheWrite || 0)          * 3.75 / 1_000_000;
      const c = costIn + costOut + costCR + costCW;
      totalCost += c;
      console.log(`ok  in=${usage.input_tokens||0} out=${usage.output_tokens||0} cr=${usage.cacheRead} cw=${usage.cacheWrite}  $${c.toFixed(4)}`);
    } catch (e) {
      console.log(`FAIL ${e.message.slice(0, 200)}`);
    }
  }
  console.log(`\nTotal: ${todo.length} stops, ~$${totalCost.toFixed(2)} run cost.`);
  console.log(`Guides written to: ${GUIDES_PATH}`);
})();
